import { setup } from "@qwinsi/utilities-js/sw";
import { version as APP_VERSION } from "../package.json";

const SUBDIRECTORY = "/tex2typst-webapp";

const precacheResources = [
    "/",
    "/index.html",
    "/main.js",
    "/style.css",
    "/icons/github-mark-white.svg",
    "/icons/notebook-icon.svg",
    "/icons/settings-icon.svg",
    "/manifest.json",
    "/favicon.png",
    "/impl-in-typst.html",
    "/cheat-sheet.html",

    "/katex.min.css",
    "/fonts/KaTeX_AMS-Regular.ttf",
    "/fonts/KaTeX_AMS-Regular.woff",
    "/fonts/KaTeX_AMS-Regular.woff2",
    "/fonts/KaTeX_Caligraphic-Bold.ttf",
    "/fonts/KaTeX_Caligraphic-Bold.woff",
    "/fonts/KaTeX_Caligraphic-Bold.woff2",
    "/fonts/KaTeX_Caligraphic-Regular.ttf",
    "/fonts/KaTeX_Caligraphic-Regular.woff",
    "/fonts/KaTeX_Caligraphic-Regular.woff2",
    "/fonts/KaTeX_Fraktur-Bold.ttf",
    "/fonts/KaTeX_Fraktur-Bold.woff",
    "/fonts/KaTeX_Fraktur-Bold.woff2",
    "/fonts/KaTeX_Fraktur-Regular.ttf",
    "/fonts/KaTeX_Fraktur-Regular.woff",
    "/fonts/KaTeX_Fraktur-Regular.woff2",
    "/fonts/KaTeX_Main-BoldItalic.ttf",
    "/fonts/KaTeX_Main-BoldItalic.woff",
    "/fonts/KaTeX_Main-BoldItalic.woff2",
    "/fonts/KaTeX_Main-Bold.ttf",
    "/fonts/KaTeX_Main-Bold.woff",
    "/fonts/KaTeX_Main-Bold.woff2",
    "/fonts/KaTeX_Main-Italic.ttf",
    "/fonts/KaTeX_Main-Italic.woff",
    "/fonts/KaTeX_Main-Italic.woff2",
    "/fonts/KaTeX_Main-Regular.ttf",
    "/fonts/KaTeX_Main-Regular.woff",
    "/fonts/KaTeX_Main-Regular.woff2",
    "/fonts/KaTeX_Math-BoldItalic.ttf",
    "/fonts/KaTeX_Math-BoldItalic.woff",
    "/fonts/KaTeX_Math-BoldItalic.woff2",
    "/fonts/KaTeX_Math-Italic.ttf",
    "/fonts/KaTeX_Math-Italic.woff",
    "/fonts/KaTeX_Math-Italic.woff2",
    "/fonts/KaTeX_SansSerif-Bold.ttf",
    "/fonts/KaTeX_SansSerif-Bold.woff",
    "/fonts/KaTeX_SansSerif-Bold.woff2",
    "/fonts/KaTeX_SansSerif-Italic.ttf",
    "/fonts/KaTeX_SansSerif-Italic.woff",
    "/fonts/KaTeX_SansSerif-Italic.woff2",
    "/fonts/KaTeX_SansSerif-Regular.ttf",
    "/fonts/KaTeX_SansSerif-Regular.woff",
    "/fonts/KaTeX_SansSerif-Regular.woff2",
    "/fonts/KaTeX_Script-Regular.ttf",
    "/fonts/KaTeX_Script-Regular.woff",
    "/fonts/KaTeX_Script-Regular.woff2",
    "/fonts/KaTeX_Size1-Regular.ttf",
    "/fonts/KaTeX_Size1-Regular.woff",
    "/fonts/KaTeX_Size1-Regular.woff2",
    "/fonts/KaTeX_Size2-Regular.ttf",
    "/fonts/KaTeX_Size2-Regular.woff",
    "/fonts/KaTeX_Size2-Regular.woff2",
    "/fonts/KaTeX_Size3-Regular.ttf",
    "/fonts/KaTeX_Size3-Regular.woff",
    "/fonts/KaTeX_Size3-Regular.woff2",
    "/fonts/KaTeX_Size4-Regular.ttf",
    "/fonts/KaTeX_Size4-Regular.woff",
    "/fonts/KaTeX_Size4-Regular.woff2",
    "/fonts/KaTeX_Typewriter-Regular.ttf",
    "/fonts/KaTeX_Typewriter-Regular.woff",
    "/fonts/KaTeX_Typewriter-Regular.woff2",
];

const prefixedResources = precacheResources.map((resource) => SUBDIRECTORY + resource);

setup(APP_VERSION, prefixedResources);
